### ISSUE TITLE
Access to Dataset-I and Dataset-IV

### ISSUE THREAD

**Issue by island255** [Siyuan-Li201/LibAM#1]
Hi, I have read your paper and got lots of inspiration. I noticed that TPL-related datasets containing large-scale projects are rare. 

Do you have a plan to open-source the full binaries of Dataset-I and Dataset-IV? This must greatly facilitate further research.

**Comment by Siyuan-Li201** [comment]
I have updated Dataset-I on github. As for Dataset-IV, due to some commercial issues, we do not plan to upload it at the moment. We agree with you that future production of a large TPL dataset containing ground truth will greatly facilitate further research. However, Dataset-IV does not include TPL reused ground truth. (Update the [dataset-I](https://drive.google.com/drive/folders/1e2yR-X9zClKVq7HOSIWlCKhKzlWjQDWy?usp=drive_link))

**Comment by island255** [comment]
I understand. Thanks for your help!
